spring.application.name=ai-dashboard

server.port=${PORT:8080}

# DB config (dynamic)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/aidashboard}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# API Key (secure way)
ai.api.key=${AI_API_KEY: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}
